services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: pokemon_tcg
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust  # This disables password authentication
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pokemon-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://ash:postgres@db:5432/pokemon_tcg
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations
      - ./backend/config.py:/app/config.py
      - ./backend/wsgi.py:/app/wsgi.py
      - ./backend/manage.py:/app/manage.py
      - ./backend/requirements.txt:/app/requirements.txt
    depends_on:
      - db
   

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: 